variation: REFERENCE # {NONE, REFERENCE}

participants:
  initial:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R 
    - S 
    - T 

flow:
  - show-length:
    - blockchain

  - delete:
      chain:
        participant: A

  - delete:
      chain:
        participant: B

  - delete:
      chain:
        participant: C

  - delete:
      chain:
        participant: D

  - delete:
      chain:
        participant: E

  - delete:
      chain:
        participant: F

  - delete:
      chain:
        participant: G

  - delete:
      chain:
        participant: H

  - delete:
      chain:
        participant: I

  - delete:
      chain:
        participant: J

  - delete:
      chain:
        participant: K

  - delete:
      chain:
        participant: L

  - delete:
      chain:
        participant: M

  - delete:
      chain:
        participant: N

  - delete:
      chain:
        participant: O

  - delete:
      chain:
        participant: P

  - delete:
      chain:
        participant: Q

  - delete:
      chain:
        participant: R

  - delete:
      chain:
        participant: S

  - delete:
      chain:
        participant: T
        
  - show-length:
    - blockchain
